- name: Deploy a web application
  hosts: db_and_web
  become: yes
  tasks:
    - name: Update the system
      apt:
        update_cache: yes
    - name: 1) Install all requried dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - include: tasks/deploy-db.yml
    - include: tasks/deploy-web.yml
    
    
